version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rcc
    ports:
      - "5432:5432"

  rcc-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: service
    environment:
      DATABASE_URL: postgres://user:password@db:5432/rcc
      APP_SECRET: "super-secret-key"
    depends_on:
      - db

  rcc-soap:
    build:
      context: .
      dockerfile: Dockerfile
      target: soap
    volumes:
      - ./games:/app/games
    ports:
      - "8080:8080"
    depends_on:
      - rcc-service
